-- Curated categorization seed data moves from classpath CSVs into tables so
-- entries can be managed at runtime (admin bulk-import endpoints) instead of
-- requiring a code deploy. Seed rows below are the exact contents of the
-- former seed/*.csv files.

CREATE TABLE curated_dictionary_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    keyword VARCHAR(120) NOT NULL UNIQUE,
    generic_name VARCHAR(120),
    category VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE brand_registry_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    normalized_key VARCHAR(120) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE categorization_benchmark_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    description VARCHAR(500) NOT NULL UNIQUE,
    expected_category VARCHAR(30) NOT NULL,
    expected_brand VARCHAR(120),
    expected_pack_size NUMERIC(12,3),
    expected_pack_unit VARCHAR(10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO curated_dictionary_entries (keyword, generic_name, category) VALUES
('arroz', 'Arroz', 'GROCERIES'),
('feijao', 'Feijão', 'GROCERIES'),
('acucar', 'Açúcar', 'GROCERIES'),
('sal', 'Sal', 'GROCERIES'),
('oleo', 'Óleo', 'GROCERIES'),
('azeite', 'Azeite', 'GROCERIES'),
('farinha', 'Farinha', 'GROCERIES'),
('macarrao', 'Macarrão', 'GROCERIES'),
('massa', 'Massa', 'GROCERIES'),
('molho', 'Molho', 'GROCERIES'),
('extrato', 'Extrato de Tomate', 'GROCERIES'),
('fuba', 'Fubá', 'GROCERIES'),
('amido', 'Amido de Milho', 'GROCERIES'),
('fermento', 'Fermento', 'GROCERIES'),
('maionese', 'Maionese', 'GROCERIES'),
('ketchup', 'Ketchup', 'GROCERIES'),
('mostarda', 'Mostarda', 'GROCERIES'),
('vinagre', 'Vinagre', 'GROCERIES'),
('biscoito', 'Biscoito', 'GROCERIES'),
('bolacha', 'Biscoito', 'GROCERIES'),
('chocolate', 'Chocolate', 'GROCERIES'),
('achocolatado', 'Achocolatado', 'GROCERIES'),
('cereal', 'Cereal', 'GROCERIES'),
('aveia', 'Aveia', 'GROCERIES'),
('granola', 'Granola', 'GROCERIES'),
('mel', 'Mel', 'GROCERIES'),
('geleia', 'Geleia', 'GROCERIES'),
('leite', 'Leite', 'MEAT_DAIRY'),
('leite condensado', 'Leite Condensado', 'GROCERIES'),
('creme de leite', 'Creme de Leite', 'MEAT_DAIRY'),
('queijo', 'Queijo', 'MEAT_DAIRY'),
('iogurte', 'Iogurte', 'MEAT_DAIRY'),
('manteiga', 'Manteiga', 'MEAT_DAIRY'),
('margarina', 'Margarina', 'MEAT_DAIRY'),
('requeijao', 'Requeijão', 'MEAT_DAIRY'),
('ovo', 'Ovo', 'MEAT_DAIRY'),
('ovos', 'Ovo', 'MEAT_DAIRY'),
('pao', 'Pão', 'BAKERY'),
('torrada', 'Torrada', 'BAKERY'),
('bolo', 'Bolo', 'BAKERY'),
('rosquinha', 'Rosquinha', 'BAKERY'),
('panettone', 'Panettone', 'BAKERY'),
('carne', 'Carne', 'MEAT_DAIRY'),
('file', 'Filé', 'MEAT_DAIRY'),
('costela', 'Costela', 'MEAT_DAIRY'),
('alcatra', 'Alcatra', 'MEAT_DAIRY'),
('patinho', 'Patinho', 'MEAT_DAIRY'),
('acem', 'Acém', 'MEAT_DAIRY'),
('linguica', 'Linguiça', 'MEAT_DAIRY'),
('salsicha', 'Salsicha', 'MEAT_DAIRY'),
('hamburguer', 'Hambúrguer', 'MEAT_DAIRY'),
('nuggets', 'Nuggets', 'MEAT_DAIRY'),
('peito frango', 'Peito de Frango', 'MEAT_DAIRY'),
('coxa frango', 'Coxa de Frango', 'MEAT_DAIRY'),
('frango', 'Frango', 'MEAT_DAIRY'),
('peixe', 'Peixe', 'MEAT_DAIRY'),
('bacalhau', 'Bacalhau', 'MEAT_DAIRY'),
('sardinha', 'Sardinha', 'MEAT_DAIRY'),
('atum', 'Atum', 'MEAT_DAIRY'),
('salmao', 'Salmão', 'MEAT_DAIRY'),
('camarao', 'Camarão', 'MEAT_DAIRY'),
('presunto', 'Presunto', 'MEAT_DAIRY'),
('mortadela', 'Mortadela', 'MEAT_DAIRY'),
('salame', 'Salame', 'MEAT_DAIRY'),
('bacon', 'Bacon', 'MEAT_DAIRY'),
('peito peru', 'Peito de Peru', 'MEAT_DAIRY'),
('tomate', 'Tomate', 'PRODUCE'),
('batata', 'Batata', 'PRODUCE'),
('cebola', 'Cebola', 'PRODUCE'),
('alho', 'Alho', 'PRODUCE'),
('cenoura', 'Cenoura', 'PRODUCE'),
('beterraba', 'Beterraba', 'PRODUCE'),
('abobrinha', 'Abobrinha', 'PRODUCE'),
('pepino', 'Pepino', 'PRODUCE'),
('pimentao', 'Pimentão', 'PRODUCE'),
('abobora', 'Abóbora', 'PRODUCE'),
('mandioca', 'Mandioca', 'PRODUCE'),
('inhame', 'Inhame', 'PRODUCE'),
('alface', 'Alface', 'PRODUCE'),
('rucula', 'Rúcula', 'PRODUCE'),
('couve', 'Couve', 'PRODUCE'),
('espinafre', 'Espinafre', 'PRODUCE'),
('brocolis', 'Brócolis', 'PRODUCE'),
('couve flor', 'Couve-flor', 'PRODUCE'),
('banana', 'Banana', 'PRODUCE'),
('maca', 'Maçã', 'PRODUCE'),
('laranja', 'Laranja', 'PRODUCE'),
('mexerica', 'Mexerica', 'PRODUCE'),
('mamao', 'Mamão', 'PRODUCE'),
('abacaxi', 'Abacaxi', 'PRODUCE'),
('melancia', 'Melancia', 'PRODUCE'),
('melao', 'Melão', 'PRODUCE'),
('uva', 'Uva', 'PRODUCE'),
('manga', 'Manga', 'PRODUCE'),
('abacate', 'Abacate', 'PRODUCE'),
('limao', 'Limão', 'PRODUCE'),
('morango', 'Morango', 'PRODUCE'),
('agua', 'Água', 'BEVERAGES'),
('agua mineral', 'Água Mineral', 'BEVERAGES'),
('refrigerante', 'Refrigerante', 'BEVERAGES'),
('coca', 'Refrigerante', 'BEVERAGES'),
('guarana', 'Refrigerante', 'BEVERAGES'),
('sprite', 'Refrigerante', 'BEVERAGES'),
('fanta', 'Refrigerante', 'BEVERAGES'),
('suco', 'Suco', 'BEVERAGES'),
('nectar', 'Néctar', 'BEVERAGES'),
('cha', 'Chá', 'BEVERAGES'),
('cafe', 'Café', 'BEVERAGES'),
('cerveja', 'Cerveja', 'BEVERAGES'),
('chope', 'Chope', 'BEVERAGES'),
('vinho', 'Vinho', 'BEVERAGES'),
('espumante', 'Espumante', 'BEVERAGES'),
('energetico', 'Energético', 'BEVERAGES'),
('isotonico', 'Isotônico', 'BEVERAGES'),
('sabao', 'Sabão', 'CLEANING'),
('sabao po', 'Sabão em Pó', 'CLEANING'),
('sabao em po', 'Sabão em Pó', 'CLEANING'),
('sabao liquido', 'Sabão Líquido', 'CLEANING'),
('detergente', 'Detergente', 'CLEANING'),
('amaciante', 'Amaciante', 'CLEANING'),
('alvejante', 'Alvejante', 'CLEANING'),
('desinfetante', 'Desinfetante', 'CLEANING'),
('desinf', 'Desinfetante', 'CLEANING'),
('agua sanitaria', 'Água Sanitária', 'CLEANING'),
('limpador', 'Limpador', 'CLEANING'),
('limp', 'Limpador', 'CLEANING'),
('multiuso', 'Limpador Multiuso', 'CLEANING'),
('veja', NULL, 'CLEANING'),
('pinho sol', 'Desinfetante', 'CLEANING'),
('pinho', 'Desinfetante', 'CLEANING'),
('cif', 'Sapólio', 'CLEANING'),
('sapon', 'Sapólio', 'CLEANING'),
('sapolio', 'Sapólio', 'CLEANING'),
('esponja', 'Esponja', 'CLEANING'),
('saco lixo', 'Saco de Lixo', 'CLEANING'),
('saco de lixo', 'Saco de Lixo', 'CLEANING'),
('papel toalha', 'Papel Toalha', 'CLEANING'),
('guardanapo', 'Guardanapo', 'OTHER'),
('alcool', 'Álcool', 'CLEANING'),
('luva', 'Luva', 'CLEANING'),
('shampoo', 'Shampoo', 'PERSONAL_CARE'),
('condicionador', 'Condicionador', 'PERSONAL_CARE'),
('sabonete', 'Sabonete', 'PERSONAL_CARE'),
('creme dental', 'Creme Dental', 'PERSONAL_CARE'),
('pasta dente', 'Creme Dental', 'PERSONAL_CARE'),
('escova dente', 'Escova de Dente', 'PERSONAL_CARE'),
('fio dental', 'Fio Dental', 'PERSONAL_CARE'),
('desodorante', 'Desodorante', 'PERSONAL_CARE'),
('absorvente', 'Absorvente', 'PERSONAL_CARE'),
('fralda', 'Fralda', 'OTHER'),
('papel higienico', 'Papel Higiênico', 'PERSONAL_CARE'),
('hidratante', 'Hidratante', 'PERSONAL_CARE'),
('protetor solar', 'Protetor Solar', 'PERSONAL_CARE'),
('algodao', 'Algodão', 'PERSONAL_CARE'),
('cotonete', 'Cotonete', 'PERSONAL_CARE'),
('lenco umedecido', 'Lenço Umedecido', 'PERSONAL_CARE'),
('milho', 'Milho', 'GROCERIES'),
('milho verde', 'Milho Verde', 'GROCERIES'),
('batata frita', 'Batata Frita', 'GROCERIES'),
('batata palha', 'Batata Palha', 'GROCERIES'),
('salgadinho', 'Salgadinho', 'GROCERIES'),
('salg', 'Salgadinho', 'GROCERIES'),
('lays', 'Salgadinho', 'GROCERIES'),
('doritos', 'Salgadinho', 'GROCERIES'),
('chips', 'Salgadinho', 'GROCERIES'),
('pipoca', 'Pipoca', 'GROCERIES'),
('bisc', 'Biscoito', 'GROCERIES'),
('oreo', 'Biscoito', 'GROCERIES'),
('club social', 'Biscoito', 'GROCERIES'),
('wafer', 'Wafer', 'GROCERIES'),
('waf', 'Wafer', 'GROCERIES'),
('pizza', 'Pizza', 'GROCERIES'),
('passata', 'Passata de Tomate', 'GROCERIES'),
('alga', 'Alga Marinha', 'GROCERIES'),
('bala', 'Bala', 'GROCERIES'),
('trufa', 'Trufa', 'GROCERIES'),
('confeito', 'Confeito', 'GROCERIES'),
('ling', 'Linguiça', 'MEAT_DAIRY'),
('fraldinha', 'Fraldinha', 'MEAT_DAIRY'),
('nata', 'Nata', 'MEAT_DAIRY'),
('cream cheese', 'Cream Cheese', 'MEAT_DAIRY'),
('cream ch', 'Cream Cheese', 'MEAT_DAIRY'),
('flan', 'Flan', 'MEAT_DAIRY'),
('salsa', 'Salsa', 'PRODUCE'),
('cebolinha', 'Cebolinha', 'PRODUCE'),
('maracuja', 'Maracujá', 'PRODUCE'),
('moranga', 'Moranga', 'PRODUCE'),
('coco seco', 'Coco', 'PRODUCE'),
('vh', 'Vinho', 'BEVERAGES'),
('abs', 'Absorvente', 'PERSONAL_CARE'),
('des dove', 'Desodorante', 'PERSONAL_CARE'),
('lava loucas', 'Lava-louças', 'CLEANING'),
('lav louca', 'Lava-louças', 'CLEANING'),
('lava roupas', 'Lava-roupas', 'CLEANING'),
('l roup', 'Lava-roupas', 'CLEANING'),
('esp', 'Esponja', 'CLEANING'),
('bebida', 'Bebida', 'BEVERAGES'),
('beb l', 'Bebida Láctea', 'MEAT_DAIRY'),
('chia', 'Chia', 'GROCERIES'),
('creme avela', 'Creme de Avelã', 'GROCERIES'),
('nutella', 'Creme de Avelã', 'GROCERIES'),
('qjo', 'Queijo', 'MEAT_DAIRY'),
('durepoxi', 'Durepóxi', 'OTHER'),
('b cer', 'Barra de Cereal', 'GROCERIES'),
('palito suico', 'Palito Suíço', 'GROCERIES'),
('p h', 'Papel Higiênico', 'PERSONAL_CARE'),
('prato sob', 'Prato', 'OTHER'),
('brinde', 'Brinde', 'OTHER'),
('vitamina', 'Vitamina', 'HEALTH'),
('gelol', 'Gelol', 'HEALTH'),
('lentilha', 'Lentilha', 'GROCERIES'),
('grao de bico', 'Grão de Bico', 'GROCERIES'),
('ervilha', 'Ervilha', 'GROCERIES'),
('soja', 'Soja', 'GROCERIES'),
('espaguete', 'Espaguete', 'GROCERIES'),
('miojo', 'Macarrão Instantâneo', 'GROCERIES'),
('polvilho', 'Polvilho', 'GROCERIES'),
('tapioca', 'Tapioca', 'GROCERIES'),
('adocante', 'Adoçante', 'GROCERIES'),
('bicarbonato', 'Bicarbonato', 'GROCERIES'),
('leite em po', 'Leite em Pó', 'GROCERIES'),
('gelatina', 'Gelatina', 'GROCERIES'),
('pudim', 'Pudim', 'GROCERIES'),
('pasta de amendoim', 'Pasta de Amendoim', 'GROCERIES'),
('amendoim', 'Amendoim', 'GROCERIES'),
('azeitona', 'Azeitona', 'GROCERIES'),
('palmito', 'Palmito', 'GROCERIES'),
('shoyu', 'Molho Shoyu', 'GROCERIES'),
('oregano', 'Orégano', 'GROCERIES'),
('canela', 'Canela', 'GROCERIES'),
('pimenta', 'Pimenta', 'GROCERIES'),
('cominho', 'Cominho', 'GROCERIES'),
('colorau', 'Colorau', 'GROCERIES'),
('caldo', 'Caldo', 'GROCERIES'),
('tempero', 'Tempero', 'GROCERIES'),
('farofa', 'Farofa', 'GROCERIES'),
('cuscuz', 'Cuscuz', 'GROCERIES'),
('lasanha', 'Lasanha', 'GROCERIES'),
('doce de leite', 'Doce de Leite', 'GROCERIES'),
('pacoca', 'Paçoca', 'GROCERIES'),
('castanha', 'Castanha', 'GROCERIES'),
('nozes', 'Nozes', 'GROCERIES'),
('uva passa', 'Uva Passa', 'GROCERIES'),
('coco ralado', 'Coco Ralado', 'GROCERIES'),
('leite de coco', 'Leite de Coco', 'GROCERIES'),
('rapadura', 'Rapadura', 'GROCERIES'),
('mistura para bolo', 'Mistura para Bolo', 'GROCERIES'),
('sagu', 'Sagu', 'GROCERIES'),
('mussarela', 'Mussarela', 'MEAT_DAIRY'),
('parmesao', 'Parmesão', 'MEAT_DAIRY'),
('provolone', 'Provolone', 'MEAT_DAIRY'),
('ricota', 'Ricota', 'MEAT_DAIRY'),
('cottage', 'Cottage', 'MEAT_DAIRY'),
('queijo prato', 'Queijo Prato', 'MEAT_DAIRY'),
('leite fermentado', 'Leite Fermentado', 'MEAT_DAIRY'),
('picanha', 'Picanha', 'MEAT_DAIRY'),
('maminha', 'Maminha', 'MEAT_DAIRY'),
('pernil', 'Pernil', 'MEAT_DAIRY'),
('lombo', 'Lombo', 'MEAT_DAIRY'),
('tilapia', 'Tilápia', 'MEAT_DAIRY'),
('coxao', 'Coxão', 'MEAT_DAIRY'),
('musculo', 'Músculo', 'MEAT_DAIRY'),
('sobrecoxa', 'Sobrecoxa', 'MEAT_DAIRY'),
('asa de frango', 'Asa de Frango', 'MEAT_DAIRY'),
('pera', 'Pera', 'PRODUCE'),
('repolho', 'Repolho', 'PRODUCE'),
('chuchu', 'Chuchu', 'PRODUCE'),
('gengibre', 'Gengibre', 'PRODUCE'),
('coentro', 'Coentro', 'PRODUCE'),
('manjericao', 'Manjericão', 'PRODUCE'),
('vagem', 'Vagem', 'PRODUCE'),
('quiabo', 'Quiabo', 'PRODUCE'),
('berinjela', 'Berinjela', 'PRODUCE'),
('agriao', 'Agrião', 'PRODUCE'),
('tangerina', 'Tangerina', 'PRODUCE'),
('figo', 'Figo', 'PRODUCE'),
('caju', 'Caju', 'PRODUCE'),
('kiwi', 'Kiwi', 'PRODUCE'),
('ameixa', 'Ameixa', 'PRODUCE'),
('pessego', 'Pêssego', 'PRODUCE'),
('caqui', 'Caqui', 'PRODUCE'),
('goiaba', 'Goiaba', 'PRODUCE'),
('acerola', 'Acerola', 'PRODUCE'),
('alho poro', 'Alho-poró', 'PRODUCE'),
('batata doce', 'Batata Doce', 'PRODUCE'),
('rabanete', 'Rabanete', 'PRODUCE'),
('lustra moveis', 'Lustra-móveis', 'CLEANING'),
('tira manchas', 'Tira-manchas', 'CLEANING'),
('cloro', 'Cloro', 'CLEANING'),
('removedor', 'Removedor', 'CLEANING'),
('desengordurante', 'Desengordurante', 'CLEANING'),
('limpa vidro', 'Limpa-vidros', 'CLEANING'),
('odorizador', 'Odorizador', 'CLEANING'),
('inseticida', 'Inseticida', 'CLEANING'),
('pano de chao', 'Pano de Chão', 'CLEANING'),
('esfregao', 'Esfregão', 'CLEANING'),
('enxaguante bucal', 'Enxaguante Bucal', 'PERSONAL_CARE'),
('barbeador', 'Barbeador', 'PERSONAL_CARE'),
('espuma de barbear', 'Espuma de Barbear', 'PERSONAL_CARE'),
('sabonete intimo', 'Sabonete Íntimo', 'PERSONAL_CARE'),
('talco', 'Talco', 'PERSONAL_CARE'),
('colonia', 'Colônia', 'PERSONAL_CARE'),
('perfume', 'Perfume', 'PERSONAL_CARE'),
('pomada assadura', 'Pomada para Assadura', 'PERSONAL_CARE'),
('mascara capilar', 'Máscara Capilar', 'PERSONAL_CARE'),
('hidratante labial', 'Hidratante Labial', 'PERSONAL_CARE'),
('agua de coco', 'Água de Coco', 'BEVERAGES'),
('agua tonica', 'Água Tônica', 'BEVERAGES'),
('vodka', 'Vodka', 'BEVERAGES'),
('whisky', 'Whisky', 'BEVERAGES'),
('cachaca', 'Cachaça', 'BEVERAGES'),
('gin', 'Gin', 'BEVERAGES'),
('rum', 'Rum', 'BEVERAGES'),
('licor', 'Licor', 'BEVERAGES'),
('refresco', 'Refresco em Pó', 'BEVERAGES'),
('suco em po', 'Suco em Pó', 'BEVERAGES'),
('mate', 'Chá Mate', 'BEVERAGES'),
('pao de forma', 'Pão de Forma', 'BAKERY'),
('pao frances', 'Pão Francês', 'BAKERY'),
('pao de queijo', 'Pão de Queijo', 'BAKERY'),
('baguete', 'Baguete', 'BAKERY'),
('croissant', 'Croissant', 'BAKERY'),
('bisnaguinha', 'Bisnaguinha', 'BAKERY'),
('pao integral', 'Pão Integral', 'BAKERY'),
('broa', 'Broa', 'BAKERY'),
('rosca', 'Rosca', 'BAKERY'),
('achoc', 'Achocolatado', 'GROCERIES'),
('az', 'Azeite', 'GROCERIES'),
('p toalha', 'Papel Toalha', 'CLEANING'),
('amac', 'Amaciante', 'CLEANING'),
('det', 'Detergente', 'CLEANING'),
('ag sanitaria', 'Água Sanitária', 'CLEANING'),
('perf r', 'Perfumador de Roupas', 'CLEANING'),
('orquidea', 'Aromatizante', 'CLEANING'),
('dipirona', 'Dipirona', 'HEALTH'),
('paracetamol', 'Paracetamol', 'HEALTH'),
('ibuprofeno', 'Ibuprofeno', 'HEALTH'),
('nimesulida', 'Nimesulida', 'HEALTH'),
('diclofenaco', 'Diclofenaco', 'HEALTH'),
('omeprazol', 'Omeprazol', 'HEALTH'),
('amoxicilina', 'Amoxicilina', 'HEALTH'),
('azitromicina', 'Azitromicina', 'HEALTH'),
('loratadina', 'Loratadina', 'HEALTH'),
('cetoprofeno', 'Cetoprofeno', 'HEALTH'),
('dorflex', 'Dorflex', 'HEALTH'),
('novalgina', 'Novalgina', 'HEALTH'),
('buscopan', 'Buscopan', 'HEALTH'),
('neosaldina', 'Neosaldina', 'HEALTH'),
('tylenol', 'Tylenol', 'HEALTH'),
('advil', 'Advil', 'HEALTH'),
('aspirina', 'Aspirina', 'HEALTH'),
('engov', 'Engov', 'HEALTH'),
('dramin', 'Dramin', 'HEALTH'),
('luftal', 'Luftal', 'HEALTH'),
('comprimido', 'Medicamento', 'HEALTH'),
('capsula', 'Medicamento', 'HEALTH'),
('capsulas', 'Medicamento', 'HEALTH'),
('drageas', 'Medicamento', 'HEALTH'),
('xarope', 'Xarope', 'HEALTH'),
('pomada', 'Pomada', 'HEALTH'),
('polivitaminico', 'Polivitamínico', 'HEALTH'),
('suplemento', 'Suplemento', 'HEALTH'),
('whey', 'Whey Protein', 'HEALTH'),
('creatina', 'Creatina', 'HEALTH'),
('colageno', 'Colágeno', 'HEALTH'),
('melatonina', 'Melatonina', 'HEALTH'),
('soro fisiologico', 'Soro Fisiológico', 'HEALTH'),
('preservativo', 'Preservativo', 'HEALTH'),
('curativo', 'Curativo', 'HEALTH'),
('gaze', 'Gaze', 'HEALTH'),
('seringa', 'Seringa', 'HEALTH'),
('termometro', 'Termômetro', 'HEALTH'),
('chuleta', 'Chuleta', 'MEAT_DAIRY'),
('miudeza', 'Miudeza', 'MEAT_DAIRY'),
('coxa', 'Coxa de Frango', 'MEAT_DAIRY'),
('bergamota', 'Bergamota', 'PRODUCE'),
('bombom', 'Bombom', 'GROCERIES'),
('choc', 'Chocolate', 'GROCERIES'),
('ultragrip', 'Aparelho de Barbear', 'PERSONAL_CARE'),
('naftalina', 'Naftalina', 'CLEANING'),
('mata ratos', 'Raticida', 'CLEANING'),
('saco xadrez', 'Saco de Lixo', 'CLEANING'),
('calca virada', 'Cueca Virada', 'BAKERY'),
('cueca virada', 'Cueca Virada', 'BAKERY'),
('racao', 'Ração', 'OTHER'),
('racao gato', 'Ração para Gato', 'OTHER'),
('racao cachorro', 'Ração para Cachorro', 'OTHER'),
('racao cao', 'Ração para Cão', 'OTHER'),
('racao felino', 'Ração Felina', 'OTHER'),
('racao canino', 'Ração Canina', 'OTHER'),
('petisco', 'Petisco para Pet', 'OTHER'),
('tapete higienico', 'Tapete Higiênico', 'OTHER'),
('areia higienica', 'Areia Higiênica', 'OTHER'),
('areia gato', 'Areia para Gato', 'OTHER'),
('comedouro', 'Comedouro', 'OTHER'),
('bebedouro pet', 'Bebedouro', 'OTHER'),
('antipulgas', 'Antipulgas', 'OTHER'),
('vermifugo', 'Vermífugo', 'HEALTH'),
('coleira antipulga', 'Coleira Antipulga', 'OTHER'),
('fraldas', 'Fralda', 'OTHER'),
('fralda descartavel', 'Fralda Descartável', 'OTHER'),
('lencos umedecidos', 'Lenço Umedecido', 'OTHER'),
('lenco umido', 'Lenço Umedecido', 'OTHER'),
('toalha umida', 'Lenço Umedecido', 'OTHER'),
('papinha', 'Papinha', 'GROCERIES'),
('papa bebe', 'Papinha', 'GROCERIES'),
('mingau', 'Mingau', 'GROCERIES'),
('mamadeira', 'Mamadeira', 'OTHER'),
('chupeta', 'Chupeta', 'OTHER'),
('mordedor', 'Mordedor', 'OTHER'),
('talco bebe', 'Talco', 'PERSONAL_CARE'),
('shampoo bebe', 'Shampoo', 'PERSONAL_CARE'),
('creme fralda', 'Creme para Fralda', 'PERSONAL_CARE'),
('pilha', 'Pilha', 'OTHER'),
('pilhas', 'Pilha', 'OTHER'),
('bateria 9v', 'Bateria', 'OTHER'),
('bateria alcalina', 'Bateria', 'OTHER'),
('lampada', 'Lâmpada', 'OTHER'),
('lampada led', 'Lâmpada LED', 'OTHER'),
('tomada', 'Tomada', 'OTHER'),
('extensao', 'Extensão Elétrica', 'OTHER'),
('cabo usb', 'Cabo USB', 'OTHER'),
('pilha alcalina', 'Pilha Alcalina', 'OTHER'),
('pilha recarregavel', 'Pilha Recarregável', 'OTHER'),
('vela', 'Vela', 'OTHER'),
('vela aromatica', 'Vela Aromática', 'OTHER'),
('incenso', 'Incenso', 'OTHER'),
('porta vela', 'Porta-Vela', 'OTHER'),
('difusor', 'Difusor de Ambiente', 'OTHER'),
('sacos de lixo', 'Saco de Lixo', 'CLEANING'),
('saco para lixo', 'Saco de Lixo', 'CLEANING'),
('filme pvc', 'Filme PVC', 'OTHER'),
('papel aluminio', 'Papel Alumínio', 'OTHER'),
('papel manteiga', 'Papel Manteiga', 'OTHER'),
('pote plastico', 'Pote', 'OTHER'),
('vasilha', 'Vasilha', 'OTHER'),
('pano de prato', 'Pano de Prato', 'CLEANING'),
('rodo', 'Rodo', 'CLEANING'),
('vassoura', 'Vassoura', 'CLEANING'),
('pano multiuso', 'Pano Multiuso', 'CLEANING'),
('luva domestica', 'Luva Doméstica', 'CLEANING'),
('remove manchas', 'Tira-Manchas', 'CLEANING'),
('limpador multiuso', 'Limpador Multiuso', 'CLEANING'),
('desentupidor', 'Desentupidor', 'CLEANING'),
('repelente insetos', 'Repelente', 'HEALTH'),
('cera assoalho', 'Cera', 'CLEANING'),
('protecao solar', 'Protetor Solar', 'PERSONAL_CARE'),
('fps', 'Protetor Solar', 'PERSONAL_CARE'),
('filtro solar', 'Protetor Solar', 'PERSONAL_CARE'),
('absorvente interno', 'Absorvente Interno', 'PERSONAL_CARE'),
('lenco de papel', 'Lenço de Papel', 'PERSONAL_CARE'),
('lencos de papel', 'Lenço de Papel', 'PERSONAL_CARE'),
('papel tissue', 'Lenço de Papel', 'PERSONAL_CARE'),
('esponja banho', 'Esponja de Banho', 'PERSONAL_CARE'),
('loofah', 'Esponja de Banho', 'PERSONAL_CARE'),
('bucha vegetal', 'Esponja de Banho', 'PERSONAL_CARE'),
('escova de cabelo', 'Escova de Cabelo', 'PERSONAL_CARE'),
('pente', 'Pente', 'PERSONAL_CARE'),
('lixa de unha', 'Lixa de Unha', 'PERSONAL_CARE'),
('aparelho de barbear', 'Aparelho de Barbear', 'PERSONAL_CARE'),
('lamina de barbear', 'Lâmina de Barbear', 'PERSONAL_CARE'),
('creme de barbear', 'Creme de Barbear', 'PERSONAL_CARE'),
('agua de colonia', 'Água de Colônia', 'PERSONAL_CARE'),
('maquiagem', 'Maquiagem', 'PERSONAL_CARE'),
('batom', 'Batom', 'PERSONAL_CARE'),
('rimel', 'Rímel', 'PERSONAL_CARE'),
('base maquiagem', 'Base', 'PERSONAL_CARE'),
('blush', 'Blush', 'PERSONAL_CARE'),
('creme hidratante', 'Creme Hidratante', 'PERSONAL_CARE'),
('hidratante corporal', 'Hidratante Corporal', 'PERSONAL_CARE'),
('oleo corporal', 'Óleo Corporal', 'PERSONAL_CARE'),
('cefalexina', 'Cefalexina', 'HEALTH'),
('atenolol', 'Atenolol', 'HEALTH'),
('losartana', 'Losartana', 'HEALTH'),
('metformina', 'Metformina', 'HEALTH'),
('anticoncepcional', 'Anticoncepcional', 'HEALTH'),
('antibiotico', 'Antibiótico', 'HEALTH'),
('antiinflamatorio', 'Anti-inflamatório', 'HEALTH'),
('pomada cicatrizante', 'Pomada Cicatrizante', 'HEALTH'),
('gel cicatrizante', 'Gel Cicatrizante', 'HEALTH'),
('spray nasal', 'Spray Nasal', 'HEALTH'),
('colirio', 'Colírio', 'HEALTH'),
('solucao salina', 'Solução Salina', 'HEALTH'),
('multivitaminico', 'Multivitamínico', 'HEALTH'),
('whey protein', 'Whey Protein', 'HEALTH'),
('albumina', 'Albumina', 'HEALTH'),
('bcaa', 'BCAA', 'HEALTH'),
('omega 3', 'Ômega 3', 'HEALTH'),
('probiotico', 'Probiótico', 'HEALTH'),
('proteico', 'Proteico', 'HEALTH'),
('energetico termogenico', 'Termogênico', 'HEALTH'),
('band aid', 'Curativo', 'HEALTH'),
('isotônico', 'Isotônico', 'BEVERAGES'),
('vinho tinto', 'Vinho Tinto', 'BEVERAGES'),
('vinho branco', 'Vinho Branco', 'BEVERAGES'),
('vinho rose', 'Vinho Rosé', 'BEVERAGES'),
('sake', 'Saquê', 'BEVERAGES'),
('pinga', 'Cachaça', 'BEVERAGES'),
('kombucha', 'Kombucha', 'BEVERAGES'),
('kefir bebida', 'Kefir', 'BEVERAGES'),
('cha gelado', 'Chá Gelado', 'BEVERAGES'),
('limonada', 'Limonada', 'BEVERAGES'),
('suco polpa', 'Suco', 'BEVERAGES'),
('polpa de fruta', 'Polpa de Fruta', 'BEVERAGES'),
('extrato vegetal', 'Extrato Vegetal', 'BEVERAGES'),
('leite vegetal', 'Leite Vegetal', 'BEVERAGES'),
('leite de aveia', 'Leite de Aveia', 'BEVERAGES'),
('leite de amêndoa', 'Leite de Amêndoa', 'BEVERAGES'),
('leite de amendoa', 'Leite de Amêndoa', 'BEVERAGES'),
('leite de coco bebida', 'Leite de Coco', 'BEVERAGES'),
('pipoca microondas', 'Pipoca de Micro-ondas', 'GROCERIES'),
('batata chips', 'Batata Chips', 'GROCERIES'),
('castanha de caju', 'Castanha de Caju', 'GROCERIES'),
('mix nuts', 'Mix de Castanhas', 'GROCERIES'),
('polpa tomate', 'Polpa de Tomate', 'GROCERIES'),
('tomate pelado', 'Tomate Pelado', 'GROCERIES'),
('mistura tempero', 'Tempero', 'GROCERIES'),
('caldo de galinha', 'Caldo de Galinha', 'GROCERIES'),
('sopa', 'Sopa', 'GROCERIES'),
('sopao', 'Sopão', 'GROCERIES'),
('maionese light', 'Maionese Light', 'GROCERIES'),
('nescau', 'Achocolatado', 'GROCERIES'),
('achocolatado po', 'Achocolatado', 'GROCERIES'),
('cappuccino', 'Cappuccino', 'GROCERIES'),
('cafe soluvel', 'Café Solúvel', 'GROCERIES'),
('cha preto', 'Chá Preto', 'GROCERIES'),
('cha verde', 'Chá Verde', 'GROCERIES'),
('cha camomila', 'Chá de Camomila', 'GROCERIES'),
('erva mate', 'Erva-Mate', 'GROCERIES'),
('chimarrao', 'Chimarrão', 'GROCERIES'),
('panetone', 'Panetone', 'BAKERY'),
('cucas', 'Cucas', 'BAKERY'),
('strudel', 'Strudel', 'BAKERY'),
('sonho', 'Sonho', 'BAKERY'),
('coxinha massa', 'Coxinha', 'BAKERY'),
('pastel assado', 'Pastel', 'BAKERY'),
('empada', 'Empada', 'BAKERY'),
('esfirra', 'Esfiha', 'BAKERY'),
('bolinho', 'Bolinho', 'BAKERY'),
('waffel', 'Waffel', 'BAKERY'),
('muffin', 'Muffin', 'BAKERY'),
('chipa', 'Chipa', 'BAKERY'),
('bisnagas', 'Bisnaguinha', 'BAKERY'),
('bolo cenoura', 'Bolo de Cenoura', 'BAKERY'),
('bolo chocolate', 'Bolo de Chocolate', 'BAKERY'),
('bolo milho', 'Bolo de Milho', 'BAKERY'),
('linguica calabresa', 'Linguiça Calabresa', 'MEAT_DAIRY'),
('copa', 'Copa', 'MEAT_DAIRY'),
('pepperoni', 'Pepperoni', 'MEAT_DAIRY'),
('frango assado', 'Frango Assado', 'MEAT_DAIRY'),
('filé frango', 'Filé de Frango', 'MEAT_DAIRY'),
('carne suina', 'Carne Suína', 'MEAT_DAIRY'),
('costelinha', 'Costelinha', 'MEAT_DAIRY'),
('bisteca', 'Bisteca', 'MEAT_DAIRY'),
('contrafile', 'Contrafilé', 'MEAT_DAIRY'),
('queijo coalho', 'Queijo Coalho', 'MEAT_DAIRY'),
('queijo parmesao', 'Queijo Parmesão', 'MEAT_DAIRY'),
('queijo provolone', 'Queijo Provolone', 'MEAT_DAIRY'),
('ovo de galinha', 'Ovo de Galinha', 'MEAT_DAIRY'),
('limonada fruta', 'Limão', 'PRODUCE'),
('aipim', 'Aipim', 'PRODUCE'),
('macaxeira', 'Macaxeira', 'PRODUCE'),
('milho espiga', 'Milho', 'PRODUCE'),
('cogumelo', 'Cogumelo', 'PRODUCE'),
('champignon', 'Champignon', 'PRODUCE'),
('sorvete', 'Sorvete', 'GROCERIES'),
('picole', 'Picolé', 'GROCERIES'),
('massa fresca', 'Massa Fresca', 'GROCERIES'),
('polenta', 'Polenta', 'GROCERIES'),
('balas', 'Balas', 'GROCERIES'),
('chiclete', 'Chiclete', 'GROCERIES'),
('extrato tomate', 'Extrato de Tomate', 'GROCERIES'),
('melado', 'Melado', 'GROCERIES'),
('tahine', 'Tahine', 'GROCERIES'),
('pasta amendoim', 'Pasta de Amendoim', 'GROCERIES'),
('biscoito recheado', 'Biscoito Recheado', 'GROCERIES'),
('biscoito agua sal', 'Biscoito Água e Sal', 'GROCERIES'),
('biscoito cream cracker', 'Biscoito Cream Cracker', 'GROCERIES'),
('macarrao instantaneo', 'Macarrão Instantâneo', 'GROCERIES'),
('sazon', 'Sazonador', 'GROCERIES'),
('caldo de carne', 'Caldo de Carne', 'GROCERIES'),
('caldo de legumes', 'Caldo de Legumes', 'GROCERIES'),
('extrato soja', 'Extrato de Soja', 'GROCERIES'),
('creme milho', 'Creme de Milho', 'GROCERIES'),
('seleta legumes', 'Seleta de Legumes', 'GROCERIES'),
('curcuma', 'Cúrcuma', 'GROCERIES'),
('curry', 'Curry', 'GROCERIES'),
('alecrim', 'Alecrim', 'GROCERIES'),
('tomilho', 'Tomilho', 'GROCERIES'),
('noz moscada', 'Noz-Moscada', 'GROCERIES'),
('cravo', 'Cravo', 'GROCERIES'),
('louro', 'Louro', 'GROCERIES'),
('pimenta do reino', 'Pimenta-do-Reino', 'GROCERIES'),
('quinoa', 'Quinoa', 'GROCERIES'),
('linhaca', 'Linhaça', 'GROCERIES'),
('gelo', 'Gelo', 'BEVERAGES'),
('proteina', 'Proteína', 'HEALTH'),
('collagen', 'Colágeno', 'HEALTH'),
('colageno hidrolisado', 'Colágeno Hidrolisado', 'HEALTH'),
('fibra', 'Fibra Alimentar', 'HEALTH'),
('prebiotico', 'Prebiótico', 'HEALTH'),
('vitamina d', 'Vitamina D', 'HEALTH'),
('vitamina c', 'Vitamina C', 'HEALTH'),
('vitamina b12', 'Vitamina B12', 'HEALTH'),
('zinco', 'Zinco', 'HEALTH'),
('magnesio', 'Magnésio', 'HEALTH'),
('ferro', 'Suplemento de Ferro', 'HEALTH'),
('acido folico', 'Ácido Fólico', 'HEALTH'),
('lanceta', 'Lanceta', 'HEALTH'),
('fita glicemia', 'Fita de Glicemia', 'HEALTH'),
('alcool 70', 'Álcool 70%', 'HEALTH'),
('alcool gel', 'Álcool em Gel', 'HEALTH'),
('palha aco', 'Palha de Aço', 'CLEANING'),
('balde', 'Balde', 'CLEANING'),
('mop', 'Mop', 'CLEANING'),
('flanela', 'Flanela', 'CLEANING'),
('desincrustante', 'Desincrustante', 'CLEANING'),
('limpa forno', 'Limpa Forno', 'CLEANING'),
('limpa pedra', 'Limpa Pedra', 'CLEANING'),
('limpa banheiro', 'Limpa Banheiro', 'CLEANING'),
('perfumador', 'Perfumador de Ambiente', 'CLEANING'),
('aromatizador', 'Aromatizador', 'CLEANING'),
('repelente ambiente', 'Repelente de Ambiente', 'CLEANING'),
('rodo mop', 'Rodo Mop', 'CLEANING'),
('creme facial', 'Creme Facial', 'PERSONAL_CARE'),
('mascara facial', 'Máscara Facial', 'PERSONAL_CARE'),
('tonico facial', 'Tônico Facial', 'PERSONAL_CARE'),
('demaquilante', 'Demaquilante', 'PERSONAL_CARE'),
('esfoliante', 'Esfoliante', 'PERSONAL_CARE'),
('primer', 'Primer', 'PERSONAL_CARE'),
('sombra', 'Sombra', 'PERSONAL_CARE'),
('delineador', 'Delineador', 'PERSONAL_CARE'),
('escova cabelo', 'Escova de Cabelo', 'PERSONAL_CARE'),
('boticario', 'Produto O Boticário', 'PERSONAL_CARE'),
('nivea', 'Nivea', 'PERSONAL_CARE'),
('lenco descartavel', 'Lenço Descartável', 'OTHER'),
('toalha papel', 'Toalha de Papel', 'OTHER'),
('garrafa termica', 'Garrafa Térmica', 'OTHER'),
('sacola plastica', 'Sacola Plástica', 'OTHER'),
('papel filme', 'Papel Filme', 'OTHER'),
('fita adesiva', 'Fita Adesiva', 'OTHER'),
('pilha aa', 'Pilha AA', 'OTHER'),
('pilha aaa', 'Pilha AAA', 'OTHER'),
('bateria', 'Bateria', 'OTHER'),
('isqueiro', 'Isqueiro', 'OTHER'),
('vela decorativa', 'Vela Decorativa', 'OTHER');

INSERT INTO brand_registry_entries (normalized_key, display_name) VALUES
('tio joao', 'Tio João'),
('tio j', 'Tio João'),
('camil', 'Camil'),
('prato fino', 'Prato Fino'),
('ype', 'Ypê'),
('veja', 'Veja'),
('pinho sol', 'Pinho Sol'),
('omo', 'Omo'),
('ariel', 'Ariel'),
('brilhante', 'Brilhante'),
('tixan', 'Tixan'),
('mr musculo', 'Mr. Músculo'),
('cif', 'Cif'),
('coala', 'Coala'),
('bombril', 'Bombril'),
('scotch brite', 'Scotch-Brite'),
('zeppelin', 'Zeppelin'),
('girandosol', 'Girandosol'),
('itambe', 'Itambé'),
('italac', 'Italac'),
('vigor', 'Vigor'),
('piracanjuba', 'Piracanjuba'),
('ninho', 'Ninho'),
('nestle', 'Nestlé'),
('parmalat', 'Parmalat'),
('elege', 'Elegê'),
('tirol', 'Tirol'),
('danone', 'Danone'),
('batavo', 'Batavo'),
('sadia', 'Sadia'),
('perdigao', 'Perdigão'),
('seara', 'Seara'),
('aurora', 'Aurora'),
('friboi', 'Friboi'),
('swift', 'Swift'),
('fgo nat', 'Friboi Natural'),
('liza', 'Liza'),
('soya', 'Soya'),
('maria', 'Maria'),
('pilao', 'Pilão'),
('melitta', 'Melitta'),
('tres coracoes', 'Três Corações'),
('3 coracoes', 'Três Corações'),
('nescafe', 'Nescafé'),
('union', 'União'),
('uniao', 'União'),
('toddy', 'Toddy'),
('nescau', 'Nescau'),
('nesquik', 'Nesquik'),
('sucrilhos', 'Sucrilhos'),
('trakinas', 'Trakinas'),
('bauducco', 'Bauducco'),
('bono', 'Bono'),
('oreo', 'Oreo'),
('negresco', 'Negresco'),
('piraque', 'Piraquê'),
('pringles', 'Pringles'),
('doritos', 'Doritos'),
('cheetos', 'Cheetos'),
('lays', 'Lays'),
('ruffles', 'Ruffles'),
('elma chips', 'Elma Chips'),
('cisne', 'Cisne'),
('quero', 'Quero'),
('predilecta', 'Predilecta'),
('pomarola', 'Pomarola'),
('heinz', 'Heinz'),
('hellmanns', 'Hellmann''s'),
('hemmer', 'Hemmer'),
('knorr', 'Knorr'),
('maggi', 'Maggi'),
('arisco', 'Arisco'),
('sazon', 'Sazón'),
('yoki', 'Yoki'),
('neston', 'Neston'),
('mucilon', 'Mucilon'),
('nestogeno', 'Nestogeno'),
('nan', 'Nan'),
('coca cola', 'Coca-Cola'),
('coca', 'Coca-Cola'),
('pepsi', 'Pepsi'),
('guarana antarctica', 'Guaraná Antarctica'),
('antarctica', 'Antarctica'),
('schweppes', 'Schweppes'),
('sukita', 'Sukita'),
('schin', 'Schin'),
('brahma', 'Brahma'),
('skol', 'Skol'),
('itaipava', 'Itaipava'),
('heineken', 'Heineken'),
('stella', 'Stella Artois'),
('corona', 'Corona'),
('budweiser', 'Budweiser'),
('amstel', 'Amstel'),
('del valle', 'Del Valle'),
('suvalan', 'Su Fresh'),
('ades', 'Ades'),
('tial', 'Tial'),
('del mar', 'Del Mar'),
('crystal', 'Crystal'),
('prata', 'Prata'),
('indaia', 'Indaiá'),
('minalba', 'Minalba'),
('colgate', 'Colgate'),
('sensodyne', 'Sensodyne'),
('oral b', 'Oral-B'),
('crest', 'Crest'),
('pantene', 'Pantene'),
('head shoulders', 'Head & Shoulders'),
('seda', 'Seda'),
('elseve', 'Elseve'),
('dove', 'Dove'),
('lux', 'Lux'),
('nivea', 'Nivea'),
('rexona', 'Rexona'),
('giovanna baby', 'Giovanna Baby'),
('johnson', 'Johnson''s'),
('gillette', 'Gillette'),
('prestobarba', 'Prestobarba'),
('schick', 'Schick'),
('sempre livre', 'Sempre Livre'),
('intimus', 'Intimus'),
('always', 'Always'),
('huggies', 'Huggies'),
('pampers', 'Pampers'),
('pomp om', 'Pom Pom'),
('mamypoko', 'Mamypoko'),
('neve', 'Neve'),
('personal', 'Personal'),
('suave', 'Suave'),
('duracell', 'Duracell'),
('panasonic', 'Panasonic'),
('philips', 'Philips'),
('3m', '3M'),
('durex', 'Durex'),
('buriti', 'Buriti'),
('zaeli', 'Zaeli'),
('tio mingote', 'Tio Mingote'),
('kicaldo', 'Kicaldo'),
('combrasil', 'Combrasil'),
('caldo bom', 'Caldo Bom'),
('maxximus', 'Maxximus'),
('broto legal', 'Broto Legal'),
('renata', 'Renata'),
('galo', 'Galo'),
('adria', 'Adria'),
('petybon', 'Petybon'),
('barilla', 'Barilla'),
('vilma', 'Vilma'),
('fortaleza', 'Fortaleza'),
('santa amalia', 'Santa Amália'),
('tirolez', 'Tirolez'),
('polenghi', 'Polenghi'),
('quata', 'Quatá'),
('pomerode', 'Pomerode'),
('frimesa', 'Frimesa'),
('verde campo', 'Verde Campo'),
('president', 'Président'),
('catupiry', 'Catupiry'),
('faixa azul', 'Faixa Azul'),
('selita', 'Selita'),
('yorgus', 'Yorgus'),
('yopro', 'Yopro'),
('activia', 'Activia'),
('nesfit', 'Nesfit'),
('lacta', 'Lacta'),
('garoto', 'Garoto'),
('hersheys', 'Hershey''s'),
('talento', 'Talento'),
('bis', 'Bis'),
('diamante negro', 'Diamante Negro'),
('chokito', 'Chokito'),
('trento', 'Trento'),
('ouro branco', 'Ouro Branco'),
('sonho de valsa', 'Sonho de Valsa'),
('serenata', 'Serenata de Amor'),
('prestigio', 'Prestígio'),
('laka', 'Laka'),
('suflair', 'Suflair'),
('batom', 'Batom'),
('halls', 'Halls'),
('mentos', 'Mentos'),
('tic tac', 'Tic Tac'),
('trident', 'Trident'),
('fini', 'Fini'),
('marilan', 'Marilan'),
('vitarella', 'Vitarella'),
('aymore', 'Aymoré'),
('triunfo', 'Triunfo'),
('mabel', 'Mabel'),
('isabela', 'Isabela'),
('toddynho', 'Toddynho'),
('kibon', 'Kibon'),
('haagen dazs', 'Häagen-Dazs'),
('diletto', 'Diletto'),
('limpol', 'Limpol'),
('yvy', 'Yvy'),
('assolan', 'Assolan'),
('cinderela', 'Cinderela'),
('comfort', 'Comfort'),
('babosa', 'Babosa'),
('flash', 'Flash'),
('lustra mor', 'Lustra Mor'),
('azulim', 'Azulim'),
('qboa', 'Qboa'),
('becel', 'Becel'),
('doriana', 'Doriana'),
('qualy', 'Qualy'),
('delicia', 'Delícia'),
('primor', 'Primor'),
('suprema', 'Suprema'),
('salada', 'Salada'),
('sinha', 'Sinhá'),
('cocamar', 'Cocamar'),
('concordia', 'Concórdia'),
('pullman', 'Pullman'),
('plusvita', 'Plusvita'),
('wickbold', 'Wickbold'),
('seven boys', 'Seven Boys'),
('visconti', 'Visconti'),
('nutrella', 'Nutrella'),
('panco', 'Panco'),
('rondelli', 'Rondelli'),
('mate leao', 'Mate Leão'),
('lipton', 'Lipton'),
('crush', 'Crush'),
('h2oh', 'H2OH'),
('gatorade', 'Gatorade'),
('powerade', 'Powerade'),
('red bull', 'Red Bull'),
('monster', 'Monster'),
('tng', 'TNG'),
('levissimo', 'Levíssimo'),
('bavaria', 'Bavaria'),
('petra', 'Petra'),
('devassa', 'Devassa'),
('eisenbahn', 'Eisenbahn'),
('colorado', 'Colorado'),
('original', 'Original'),
('imperio', 'Império'),
('cacildis', 'Cacildis'),
('salton', 'Salton'),
('miolo', 'Miolo'),
('casa valduga', 'Casa Valduga'),
('garibaldi', 'Garibaldi'),
('aurora vinhos', 'Aurora Vinhos'),
('sao mateus', 'São Mateus'),
('51', '51'),
('ypióca', 'Ypióca'),
('ypioca', 'Ypióca'),
('velho barreiro', 'Velho Barreiro'),
('sagatiba', 'Sagatiba'),
('cafe do ponto', 'Café do Ponto'),
('caboclo', 'Caboclo'),
('iguacu', 'Iguaçu'),
('brasileiro', 'Brasileiro'),
('santa clara', 'Santa Clara'),
('utam', 'Utam'),
('otima', 'Ótima'),
('pedigree', 'Pedigree'),
('whiskas', 'Whiskas'),
('royal canin', 'Royal Canin'),
('pro plan', 'Pro Plan'),
('premier', 'Premier'),
('faro', 'Faro'),
('foster', 'Foster'),
('friskies', 'Friskies'),
('nutram', 'Nutram'),
('golden', 'Golden'),
('biofresh', 'Biofresh'),
('gran plus', 'Gran Plus'),
('formula natural', 'Fórmula Natural'),
('n d', 'N&D'),
('hercosul', 'Hercosul'),
('salon line', 'Salon Line'),
('tresemme', 'Tresemmé'),
('old spice', 'Old Spice'),
('bozzano', 'Bozzano'),
('avanco', 'Avanço'),
('herbal essences', 'Herbal Essences'),
('clear', 'Clear'),
('monange', 'Monange'),
('loreal', 'L''Oréal'),
('neutrogena', 'Neutrogena'),
('sundown', 'Sundown'),
('cetaphil', 'Cetaphil'),
('granado', 'Granado'),
('phebo', 'Phebo'),
('lifebuoy', 'Lifebuoy'),
('asepxia', 'Asepxia'),
('linea', 'Linea'),
('adocon', 'Adoçon'),
('cisne sal', 'Cisne'),
('diana', 'Diana'),
('norsal', 'Norsal'),
('caravelas', 'Caravelas'),
('da barra', 'Da Barra'),
('zero cal', 'Zero Cal'),
('finn', 'Finn'),
('stevia', 'Stévia'),
('cepera', 'Cepêra'),
('karo', 'Karo'),
('sabor cor', 'Sabor & Cor'),
('salsaretti', 'Salsaretti'),
('tarantino', 'Tarantino'),
('fugini', 'Fugini'),
('bonare', 'Bonare'),
('junior', 'Junior'),
('coronado', 'Coronado'),
('mercosul', 'Mercosul'),
('ajinomoto', 'Ajinomoto'),
('mitsui', 'Mitsui'),
('sakura', 'Sakura'),
('tachibana', 'Tachibana'),
('mae terra', 'Mãe Terra'),
('jasmine', 'Jasmine'),
('belive', 'Belive'),
('bella gula', 'Bella Gula'),
('nutri ervas', 'Nutri Ervas'),
('quaker', 'Quaker'),
('all bran', 'All-Bran'),
('danubio', 'Danúbio'),
('s clara', 'Santa Clara'),
('frigol', 'Frigol'),
('excelsior', 'Excelsior'),
('neugebauer', 'Neugebauer'),
('grostoline', 'Grostoline'),
('lider do sul', 'Líder do Sul'),
('yema', 'Yema'),
('mercatto', 'Mercatto'),
('althaia', 'Althaia'),
('dolgener', 'Dolgener'),
('dolg', 'Dolgener'),
('keep cooler', 'Keep Cooler'),
('tramontina', 'Tramontina'),
('tram', 'Tramontina'),
('nutella', 'Nutella'),
('loctite', 'Loctite'),
('primod', 'Primod'),
('vapza', 'Vapza'),
('swift kitchen', 'Swift Kitchen'),
('pifpaf', 'Pif Paf'),
('seara gourmet', 'Seara Gourmet'),
('sadia hot pocket', 'Sadia Hot Pocket'),
('turma da monica', 'Turma da Mônica'),
('johnsons baby', 'Johnson''s Baby'),
('mustela', 'Mustela'),
('penaten', 'Penaten'),
('pomp om baby', 'Pom Pom Baby'),
('spaten', 'Spaten'),
('aminna', 'Aminna'),
('natural life', 'Natural Life'),
('naturallife', 'Natural Life'),
('da pedra', 'Da Pedra'),
('molico', 'Molico'),
('ritter', 'Ritter'),
('becker', 'Becker'),
('wedel', 'E. Wedel'),
('naturovos', 'Naturovos'),
('coqueiro', 'Coqueiro'),
('capellini', 'Capellini'),
('coamo', 'Coamo'),
('kicoco', 'Kicoco'),
('chandelle', 'Chandelle'),
('mu mu', 'Mu-Mu'),
('naturale', 'Naturale'),
('barao', 'Barão'),
('lebon', 'Lebon'),
('tutti', 'Tutti'),
('majestade', 'Majestade'),
('romena', 'Romena'),
('mccain', 'McCain'),
('mc cain', 'McCain'),
('vitalin', 'Vitalin'),
('vitaliv', 'Vitaliv'),
('turra', 'Turra'),
('bob', 'Bob'),
('oderich', 'Oderich'),
('iaronka', 'Iaronka'),
('prime', 'Prime'),
('p foods', 'P. Foods'),
('gil', 'Da Gil'),
('pirac', 'Piracanjuba'),
('zymil', 'Zymil'),
('scotti', 'Scotti'),
('b brasil', 'Bom Brasil'),
('bom brasil', 'Bom Brasil'),
('d aguirre', 'D''Aguirre'),
('utilo', 'Utilo'),
('v macia', 'Vila Maciça'),
('garota', 'Garota'),
('3corac', 'Três Corações'),
('andorinha', 'Andorinha'),
('divine', 'Divine'),
('sprite', 'Sprite'),
('m terra', 'Mãe Terra'),
('natureza pura', 'Natureza Pura'),
('s livre', 'Sempre Livre'),
('zaffari', 'Zaffari'),
('marquez', 'Marquez'),
('marq', 'Marquez'),
('bombay', 'Bombay');

INSERT INTO categorization_benchmark_entries (description, expected_category, expected_brand, expected_pack_size, expected_pack_unit) VALUES
('SAL REFINADO EXTRA IOD CISNE 1KG', 'GROCERIES', 'Cisne', 1, 'KG'),
('ARROZ TIO J TP1 5KG', 'GROCERIES', NULL, 5, 'KG'),
('MILHO VERDE 700G', 'GROCERIES', NULL, 700, 'G'),
('MILHO VERDE 200G', 'GROCERIES', NULL, 200, 'G'),
('BISC CLUB SOCIAL ORIGINAL 288G', 'GROCERIES', NULL, 288, 'G'),
('BISC OREO RECH BAUN 270G', 'GROCERIES', NULL, 270, 'G'),
('BISC MANTEIGA 200G', 'GROCERIES', NULL, 200, 'G'),
('BATATA FRITA AIR FRYER', 'GROCERIES', NULL, NULL, NULL),
('SALG LAYS CLASSICA 96G', 'GROCERIES', NULL, 96, 'G'),
('PIZZA SADIA CALABRESA 460G', 'GROCERIES', 'Sadia', 460, 'G'),
('PASSATA MERCATTO 680G', 'GROCERIES', NULL, 680, 'G'),
('ALGA MAR YAKINORI 10F/27G', 'GROCERIES', NULL, NULL, NULL),
('LEITE ITALAC INT 1L', 'MEAT_DAIRY', 'Italac', 1, 'L'),
('MANTEIGA AVIACAO 200G', 'MEAT_DAIRY', NULL, 200, 'G'),
('LING CAL EXCELSIOR FIN DEF 215G', 'MEAT_DAIRY', NULL, 215, 'G'),
('FRALDINHA FRIGOL EF', 'MEAT_DAIRY', NULL, NULL, NULL),
('NATA S.CLARA 300G', 'MEAT_DAIRY', NULL, 300, 'G'),
('CREAM CH DANUBIO TRAD 300G', 'MEAT_DAIRY', NULL, 300, 'G'),
('SALSA', 'PRODUCE', NULL, NULL, NULL),
('CEBOLINHA', 'PRODUCE', NULL, NULL, NULL),
('MARACUJA AZEDO GRANEL', 'PRODUCE', NULL, NULL, NULL),
('MORANGA CABOTIA PRIMOD HIG 500G', 'PRODUCE', NULL, 500, 'G'),
('BATATA INGLESA GRANEL', 'PRODUCE', NULL, NULL, NULL),
('LIMP VEJA PERF ENVOLVENTE 2L', 'CLEANING', 'Veja', 2, 'L'),
('DESINF PINHO SOL NAT LAVANDA 1L', 'CLEANING', NULL, 1, 'L'),
('SAPON CREM CIF LIM 450ML', 'CLEANING', 'Cif', 450, 'ML'),
('ALCOOL LIQ ZEPPELIN ECOBAC 46 1L', 'CLEANING', NULL, 1, 'L'),
('SACO LIXO UTILO 50L C/30', 'CLEANING', NULL, NULL, NULL),
('LAV LOUCA YPE COCO 500ML', 'CLEANING', NULL, 500, 'ML'),
('COALA CHA BRANCO AER400ML', 'BEVERAGES', NULL, NULL, NULL),
('VH AURORA MALVASIA TARDIA 500ML', 'BEVERAGES', 'Aurora', 500, 'ML'),
('ABS S.LIVRE CONF NOT C/A C/32', 'PERSONAL_CARE', NULL, NULL, NULL),
('DES DOVE ORIGINAL 50ML', 'PERSONAL_CARE', 'Dove', 50, 'ML'),
('SHAMPOO SEDA RECONSTRUCAO 325ML', 'PERSONAL_CARE', 'Seda', 325, 'ML'),
('A.GADO CHULETA kg', 'MEAT_DAIRY', NULL, NULL, NULL),
('A.GADO MIUDEZA kg', 'MEAT_DAIRY', NULL, NULL, NULL),
('A.COXA SOBR COOP kg', 'MEAT_DAIRY', NULL, NULL, NULL),
('F.BERGAMOTA PONKAM kg', 'PRODUCE', NULL, NULL, NULL),
('BOMBOM LACTA SONHO DE VALSA 20g', 'GROCERIES', NULL, NULL, NULL),
('CHOC GRAN NUTRI&WIEDER 100g', 'GROCERIES', NULL, NULL, NULL),
('APARELHO PRESTO ULTRAGRIP FIXA', 'PERSONAL_CARE', NULL, NULL, NULL),
('NAFTALINA SANILAR 50g', 'CLEANING', NULL, NULL, NULL),
('INSET MAT INSET ISCA MATA RATOS 25g', 'CLEANING', NULL, NULL, NULL),
('P.CALCA VIRADA kg', 'BAKERY', NULL, NULL, NULL),
('SACO XADREZ LAVADO 43CM 60cm', 'CLEANING', NULL, NULL, NULL);
