-- The Open Food Facts brand data proved too noisy to derive the brand registry
-- from (short/stopword tokens like 'de', 'nat', 'barra' caused false matches).
-- Restore the registry to the curated baseline and tag rows with a source so a
-- future derivation can be cleaned up selectively.
ALTER TABLE brand_registry_entries ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'CURATED';

DELETE FROM brand_registry_entries;

INSERT INTO brand_registry_entries (normalized_key, display_name) VALUES
('tio joao', 'Tio João'),
('tio j', 'Tio João'),
('camil', 'Camil'),
('prato fino', 'Prato Fino'),
('ype', 'Ypê'),
('veja', 'Veja'),
('pinho sol', 'Pinho Sol'),
('omo', 'Omo'),
('ariel', 'Ariel'),
('brilhante', 'Brilhante'),
('tixan', 'Tixan'),
('mr musculo', 'Mr. Músculo'),
('cif', 'Cif'),
('coala', 'Coala'),
('bombril', 'Bombril'),
('scotch brite', 'Scotch-Brite'),
('zeppelin', 'Zeppelin'),
('girandosol', 'Girandosol'),
('itambe', 'Itambé'),
('italac', 'Italac'),
('vigor', 'Vigor'),
('piracanjuba', 'Piracanjuba'),
('ninho', 'Ninho'),
('nestle', 'Nestlé'),
('parmalat', 'Parmalat'),
('elege', 'Elegê'),
('tirol', 'Tirol'),
('danone', 'Danone'),
('batavo', 'Batavo'),
('sadia', 'Sadia'),
('perdigao', 'Perdigão'),
('seara', 'Seara'),
('aurora', 'Aurora'),
('friboi', 'Friboi'),
('swift', 'Swift'),
('fgo nat', 'Friboi Natural'),
('liza', 'Liza'),
('soya', 'Soya'),
('maria', 'Maria'),
('pilao', 'Pilão'),
('melitta', 'Melitta'),
('tres coracoes', 'Três Corações'),
('3 coracoes', 'Três Corações'),
('nescafe', 'Nescafé'),
('union', 'União'),
('uniao', 'União'),
('toddy', 'Toddy'),
('nescau', 'Nescau'),
('nesquik', 'Nesquik'),
('sucrilhos', 'Sucrilhos'),
('trakinas', 'Trakinas'),
('bauducco', 'Bauducco'),
('bono', 'Bono'),
('oreo', 'Oreo'),
('negresco', 'Negresco'),
('piraque', 'Piraquê'),
('pringles', 'Pringles'),
('doritos', 'Doritos'),
('cheetos', 'Cheetos'),
('lays', 'Lays'),
('ruffles', 'Ruffles'),
('elma chips', 'Elma Chips'),
('cisne', 'Cisne'),
('quero', 'Quero'),
('predilecta', 'Predilecta'),
('pomarola', 'Pomarola'),
('heinz', 'Heinz'),
('hellmanns', 'Hellmann''s'),
('hemmer', 'Hemmer'),
('knorr', 'Knorr'),
('maggi', 'Maggi'),
('arisco', 'Arisco'),
('sazon', 'Sazón'),
('yoki', 'Yoki'),
('neston', 'Neston'),
('mucilon', 'Mucilon'),
('nestogeno', 'Nestogeno'),
('nan', 'Nan'),
('coca cola', 'Coca-Cola'),
('coca', 'Coca-Cola'),
('pepsi', 'Pepsi'),
('guarana antarctica', 'Guaraná Antarctica'),
('antarctica', 'Antarctica'),
('schweppes', 'Schweppes'),
('sukita', 'Sukita'),
('schin', 'Schin'),
('brahma', 'Brahma'),
('skol', 'Skol'),
('itaipava', 'Itaipava'),
('heineken', 'Heineken'),
('stella', 'Stella Artois'),
('corona', 'Corona'),
('budweiser', 'Budweiser'),
('amstel', 'Amstel'),
('del valle', 'Del Valle'),
('suvalan', 'Su Fresh'),
('ades', 'Ades'),
('tial', 'Tial'),
('del mar', 'Del Mar'),
('crystal', 'Crystal'),
('prata', 'Prata'),
('indaia', 'Indaiá'),
('minalba', 'Minalba'),
('colgate', 'Colgate'),
('sensodyne', 'Sensodyne'),
('oral b', 'Oral-B'),
('crest', 'Crest'),
('pantene', 'Pantene'),
('head shoulders', 'Head & Shoulders'),
('seda', 'Seda'),
('elseve', 'Elseve'),
('dove', 'Dove'),
('lux', 'Lux'),
('nivea', 'Nivea'),
('rexona', 'Rexona'),
('giovanna baby', 'Giovanna Baby'),
('johnson', 'Johnson''s'),
('gillette', 'Gillette'),
('prestobarba', 'Prestobarba'),
('schick', 'Schick'),
('sempre livre', 'Sempre Livre'),
('intimus', 'Intimus'),
('always', 'Always'),
('huggies', 'Huggies'),
('pampers', 'Pampers'),
('pomp om', 'Pom Pom'),
('mamypoko', 'Mamypoko'),
('neve', 'Neve'),
('personal', 'Personal'),
('suave', 'Suave'),
('duracell', 'Duracell'),
('panasonic', 'Panasonic'),
('philips', 'Philips'),
('3m', '3M'),
('durex', 'Durex'),
('buriti', 'Buriti'),
('zaeli', 'Zaeli'),
('tio mingote', 'Tio Mingote'),
('kicaldo', 'Kicaldo'),
('combrasil', 'Combrasil'),
('caldo bom', 'Caldo Bom'),
('maxximus', 'Maxximus'),
('broto legal', 'Broto Legal'),
('renata', 'Renata'),
('galo', 'Galo'),
('adria', 'Adria'),
('petybon', 'Petybon'),
('barilla', 'Barilla'),
('vilma', 'Vilma'),
('fortaleza', 'Fortaleza'),
('santa amalia', 'Santa Amália'),
('tirolez', 'Tirolez'),
('polenghi', 'Polenghi'),
('quata', 'Quatá'),
('pomerode', 'Pomerode'),
('frimesa', 'Frimesa'),
('verde campo', 'Verde Campo'),
('president', 'Président'),
('catupiry', 'Catupiry'),
('faixa azul', 'Faixa Azul'),
('selita', 'Selita'),
('yorgus', 'Yorgus'),
('yopro', 'Yopro'),
('activia', 'Activia'),
('nesfit', 'Nesfit'),
('lacta', 'Lacta'),
('garoto', 'Garoto'),
('hersheys', 'Hershey''s'),
('talento', 'Talento'),
('bis', 'Bis'),
('diamante negro', 'Diamante Negro'),
('chokito', 'Chokito'),
('trento', 'Trento'),
('ouro branco', 'Ouro Branco'),
('sonho de valsa', 'Sonho de Valsa'),
('serenata', 'Serenata de Amor'),
('prestigio', 'Prestígio'),
('laka', 'Laka'),
('suflair', 'Suflair'),
('batom', 'Batom'),
('halls', 'Halls'),
('mentos', 'Mentos'),
('tic tac', 'Tic Tac'),
('trident', 'Trident'),
('fini', 'Fini'),
('marilan', 'Marilan'),
('vitarella', 'Vitarella'),
('aymore', 'Aymoré'),
('triunfo', 'Triunfo'),
('mabel', 'Mabel'),
('isabela', 'Isabela'),
('toddynho', 'Toddynho'),
('kibon', 'Kibon'),
('haagen dazs', 'Häagen-Dazs'),
('diletto', 'Diletto'),
('limpol', 'Limpol'),
('yvy', 'Yvy'),
('assolan', 'Assolan'),
('cinderela', 'Cinderela'),
('comfort', 'Comfort'),
('babosa', 'Babosa'),
('flash', 'Flash'),
('lustra mor', 'Lustra Mor'),
('azulim', 'Azulim'),
('qboa', 'Qboa'),
('becel', 'Becel'),
('doriana', 'Doriana'),
('qualy', 'Qualy'),
('delicia', 'Delícia'),
('primor', 'Primor'),
('suprema', 'Suprema'),
('salada', 'Salada'),
('sinha', 'Sinhá'),
('cocamar', 'Cocamar'),
('concordia', 'Concórdia'),
('pullman', 'Pullman'),
('plusvita', 'Plusvita'),
('wickbold', 'Wickbold'),
('seven boys', 'Seven Boys'),
('visconti', 'Visconti'),
('nutrella', 'Nutrella'),
('panco', 'Panco'),
('rondelli', 'Rondelli'),
('mate leao', 'Mate Leão'),
('lipton', 'Lipton'),
('crush', 'Crush'),
('h2oh', 'H2OH'),
('gatorade', 'Gatorade'),
('powerade', 'Powerade'),
('red bull', 'Red Bull'),
('monster', 'Monster'),
('tng', 'TNG'),
('levissimo', 'Levíssimo'),
('bavaria', 'Bavaria'),
('petra', 'Petra'),
('devassa', 'Devassa'),
('eisenbahn', 'Eisenbahn'),
('colorado', 'Colorado'),
('original', 'Original'),
('imperio', 'Império'),
('cacildis', 'Cacildis'),
('salton', 'Salton'),
('miolo', 'Miolo'),
('casa valduga', 'Casa Valduga'),
('garibaldi', 'Garibaldi'),
('aurora vinhos', 'Aurora Vinhos'),
('sao mateus', 'São Mateus'),
('51', '51'),
('ypióca', 'Ypióca'),
('ypioca', 'Ypióca'),
('velho barreiro', 'Velho Barreiro'),
('sagatiba', 'Sagatiba'),
('cafe do ponto', 'Café do Ponto'),
('caboclo', 'Caboclo'),
('iguacu', 'Iguaçu'),
('brasileiro', 'Brasileiro'),
('santa clara', 'Santa Clara'),
('utam', 'Utam'),
('otima', 'Ótima'),
('pedigree', 'Pedigree'),
('whiskas', 'Whiskas'),
('royal canin', 'Royal Canin'),
('pro plan', 'Pro Plan'),
('premier', 'Premier'),
('faro', 'Faro'),
('foster', 'Foster'),
('friskies', 'Friskies'),
('nutram', 'Nutram'),
('golden', 'Golden'),
('biofresh', 'Biofresh'),
('gran plus', 'Gran Plus'),
('formula natural', 'Fórmula Natural'),
('n d', 'N&D'),
('hercosul', 'Hercosul'),
('salon line', 'Salon Line'),
('tresemme', 'Tresemmé'),
('old spice', 'Old Spice'),
('bozzano', 'Bozzano'),
('avanco', 'Avanço'),
('herbal essences', 'Herbal Essences'),
('clear', 'Clear'),
('monange', 'Monange'),
('loreal', 'L''Oréal'),
('neutrogena', 'Neutrogena'),
('sundown', 'Sundown'),
('cetaphil', 'Cetaphil'),
('granado', 'Granado'),
('phebo', 'Phebo'),
('lifebuoy', 'Lifebuoy'),
('asepxia', 'Asepxia'),
('linea', 'Linea'),
('adocon', 'Adoçon'),
('cisne sal', 'Cisne'),
('diana', 'Diana'),
('norsal', 'Norsal'),
('caravelas', 'Caravelas'),
('da barra', 'Da Barra'),
('zero cal', 'Zero Cal'),
('finn', 'Finn'),
('stevia', 'Stévia'),
('cepera', 'Cepêra'),
('karo', 'Karo'),
('sabor cor', 'Sabor & Cor'),
('salsaretti', 'Salsaretti'),
('tarantino', 'Tarantino'),
('fugini', 'Fugini'),
('bonare', 'Bonare'),
('junior', 'Junior'),
('coronado', 'Coronado'),
('mercosul', 'Mercosul'),
('ajinomoto', 'Ajinomoto'),
('mitsui', 'Mitsui'),
('sakura', 'Sakura'),
('tachibana', 'Tachibana'),
('mae terra', 'Mãe Terra'),
('jasmine', 'Jasmine'),
('belive', 'Belive'),
('bella gula', 'Bella Gula'),
('nutri ervas', 'Nutri Ervas'),
('quaker', 'Quaker'),
('all bran', 'All-Bran'),
('danubio', 'Danúbio'),
('s clara', 'Santa Clara'),
('frigol', 'Frigol'),
('excelsior', 'Excelsior'),
('neugebauer', 'Neugebauer'),
('grostoline', 'Grostoline'),
('lider do sul', 'Líder do Sul'),
('yema', 'Yema'),
('mercatto', 'Mercatto'),
('althaia', 'Althaia'),
('dolgener', 'Dolgener'),
('dolg', 'Dolgener'),
('keep cooler', 'Keep Cooler'),
('tramontina', 'Tramontina'),
('tram', 'Tramontina'),
('nutella', 'Nutella'),
('loctite', 'Loctite'),
('primod', 'Primod'),
('vapza', 'Vapza'),
('swift kitchen', 'Swift Kitchen'),
('pifpaf', 'Pif Paf'),
('seara gourmet', 'Seara Gourmet'),
('sadia hot pocket', 'Sadia Hot Pocket'),
('turma da monica', 'Turma da Mônica'),
('johnsons baby', 'Johnson''s Baby'),
('mustela', 'Mustela'),
('penaten', 'Penaten'),
('pomp om baby', 'Pom Pom Baby'),
('spaten', 'Spaten'),
('aminna', 'Aminna'),
('natural life', 'Natural Life'),
('naturallife', 'Natural Life'),
('da pedra', 'Da Pedra'),
('molico', 'Molico'),
('ritter', 'Ritter'),
('becker', 'Becker'),
('wedel', 'E. Wedel'),
('naturovos', 'Naturovos'),
('coqueiro', 'Coqueiro'),
('capellini', 'Capellini'),
('coamo', 'Coamo'),
('kicoco', 'Kicoco'),
('chandelle', 'Chandelle'),
('mu mu', 'Mu-Mu'),
('naturale', 'Naturale'),
('barao', 'Barão'),
('lebon', 'Lebon'),
('tutti', 'Tutti'),
('majestade', 'Majestade'),
('romena', 'Romena'),
('mccain', 'McCain'),
('mc cain', 'McCain'),
('vitalin', 'Vitalin'),
('vitaliv', 'Vitaliv'),
('turra', 'Turra'),
('bob', 'Bob'),
('oderich', 'Oderich'),
('iaronka', 'Iaronka'),
('prime', 'Prime'),
('p foods', 'P. Foods'),
('gil', 'Da Gil'),
('pirac', 'Piracanjuba'),
('zymil', 'Zymil'),
('scotti', 'Scotti'),
('b brasil', 'Bom Brasil'),
('bom brasil', 'Bom Brasil'),
('d aguirre', 'D''Aguirre'),
('utilo', 'Utilo'),
('v macia', 'Vila Maciça'),
('garota', 'Garota'),
('3corac', 'Três Corações'),
('andorinha', 'Andorinha'),
('divine', 'Divine'),
('sprite', 'Sprite'),
('m terra', 'Mãe Terra'),
('natureza pura', 'Natureza Pura'),
('s livre', 'Sempre Livre'),
('zaffari', 'Zaffari'),
('marquez', 'Marquez'),
('marq', 'Marquez'),
('bombay', 'Bombay');
